name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      # - uses: actions/checkout@v3
      #   with:
      #     submodules: true
      #     lfs: false
      # - name: Build And Deploy
      #   id: builddeploy
      #   uses: Azure/static-web-apps-deploy@v1
      #   with:
      #     azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_HILL_0A63CB603 }}
      #     repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
      #     action: "upload"
      #     ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
      #     # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
      #     app_location: "./src/Asteroids" # App source code path
      #     api_location: "" # Api source code path - optional
      #     output_location: "angular.json#$.projects[*].architect.build.options.outputPath" # Built app content directory - optional
      #     ###### End of Repository/Build Configurations ######
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: NPM install
        shell: pwsh
        working-directory: ./src/Asteroids
        run: npm ci --no-fund --loglevel error

      - name: Build
        shell: pwsh
        working-directory: src/Asteroids
        run: npm run build

      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_HILL_0A63CB603 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          skip_app_build: true
          skip_api_build: true
          output_location: ''
          app_location: './src/Asteroids/dist'
          config_file_location: './src/Asteroids'

