name: Asteroids CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-deploy-ui:
    runs-on: ubuntu-latest
    name: Build and Deploy UI
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: NPM install
        working-directory: ./src/Asteroids
        run: npm ci --no-fund --loglevel error

      - name: Build
        working-directory: src/Asteroids
        run: npm run build -- --configuration production

      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_HILL_0A63CB603 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          skip_app_build: true
          skip_api_build: true
          output_location: ""
          app_location: "./src/Asteroids/dist/asteroids/browser"
          config_file_location: "./src/Asteroids"

  build-deploy-api:
    runs-on: ubuntu-latest
    name: Build and Deploy API
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp
        working-directory: src/AsteroidHub

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "app-asteroids"
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7EB4568519894F02890C013E4A726053 }}
          package: ${{env.DOTNET_ROOT}}/myapp
