name: Deploy UI (Static Web App)

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: NPM install
        shell: pwsh
        working-directory: ./src/Asteroids
        run: npm ci --no-fund --loglevel error

      - name: Build
        shell: pwsh
        working-directory: src/Asteroids
        run: npm run build

      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_HILL_0A63CB603 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          skip_app_build: true
          skip_api_build: true
          output_location: ''
          app_location: './src/Asteroids/dist/asteroids/browser'
          config_file_location: './src/Asteroids'

